### PR TITLE
Fixes #11 but should not be used

### LINKED ISSUE #11: No icons shown on files for "icon view" and "compact list view"
view --> view as icons 
view --> view as compact

both do not show icons on the files

### PR DESCRIPTION
**Pull request by alexxcons**
Actually this is not really a pull request. It's just a demonstartor to show that #11 is a timing-issue

### CODE REVIEW

**Comment by andreldm** [comment]
I'll take a look as soon as possible

**Comment by alexxcons** [comment]
Since it seems to be a timing issue, I hope the fix works at all for you

**Comment by alexxcons** [comment]
There seems to be a even simpler patch. Just comment out the following if-statement, leave the rest like it is:
if (gdk_rectangle_intersect (&clip_area, &icon_area, &draw_area))

It looks like the intersection area of the rectangles is so small, that nothing is painted there.

**Comment by alexxcons** [comment]
Ok, I have it. It only works if draw-area is complete rubbish or uninitialized .... gdk_rectangle_intersect fills the draw area with stuff that makes sense, thats why the bug vanishes when the line is removed.

Later gdk_cairo_rectangle (cr, &draw_area); draws a rectangle to draw area ... directly over the pixbuf which was drawn one line before ... and that only works with proper data for draw_area.

I dont think that this rectangle is needed. Seems to work fine by only loading the pixbuf .. new pull request incoming. However I still dont know why detailed view works with that rectangle.

**Comment by andreldm** [comment]
Nice, thanks for debugging this. I'm no GTK/GDK/Cairo expert, once you create the PR, I'll ask people on #xfce-dev (or feel free to do so).

**Comment by alexxcons** [comment]
Ok, here we go: https://github.com/andreldm/thunar/pull/20 .. I'll close this one.   As well the first time for me to mess around with Cairo =)
.. I just asked for review on  #xfce-dev

**Pull request closed without merging**
