### PR TITLE
fixes 8 second delay on logout when thunar got started in daemon mode

### LINKED ISSUE #30: 8seconds delay on logout when thunar got started in daemon mode
Reported by ninetls
If thunar is killed `pkill Thunar` before logout everything is fine

### PR DESCRIPTION
**Pull request by alexxcons**
fixes #30 
Before merge,  I would like to check if there are other possibilities to handle logout on g_application_hold()  ... just created some [Stack-Overflow Question](https://stackoverflow.com/questions/44913967/gtk3-logout-during-g-application-hold)

I could check for Error on line 274 ... but actually I dont know to where I should write an error in thunar, if one appears .. you have any idea ?

### CODE REVIEW

**Comment by alexxcons** [comment]
Actually ( advice from ninetls ) it should not be required to make use of system-calls: Check how it was done in thunar-gtk2 and figure out why it cannot be solved the same / a similar way

**Comment by alexxcons** [comment]
Ok, it looks like this fix only fixes the symptoms of the problem, not the problem itself.

The actual problem seems to be, that the main-loop was shifted to the application-class ( gtk_main() was replaced by g_application_run() in main.c )

I will need to further check how/if that can be reverted. ( "git revert" leaves me with chaos code )  ... I will try to prepare another pull-request.

**Comment by alexxcons** [comment]
Ok, while working on the revert I realized some problems:
Revert the usage of GtkApplication would have some far reaching consequences. E.g. I as well need to revert "replace dbus-glib with GDBus 7050f279", since it seems to be not foreseen by gtk3 to use GDBus without having a GtkApplication ( or at least it is not the default-case and will require alot of extra-work)


So as far, as I can say, the options are:

1. As well revert 7050f279 and continue to live with dbus-glib instead of GDBus ( which is not recommended by gtk )
2. Use the "hook on SIGHUP fix" for now and ask the GTK-maintainers if they can add an option for a "graceful shutdown on SIGHUP while on hold" into the next gtk-version.
3. Do alot of extra-work in order hopefully have GDBus together with gtk_main()

I currently feel like 2 would be the most reasonable. Maybe first ask the GTK-team how they would handle the problem.

What would be your choice ?

**Comment by andreldm** [comment]
IHMO, if the only side effect is the ~8 seconds delay on logout, then definitely option 1 is a no go.
Option 3 is not a well known solution, so for the moment (finish the port!) a well-tested workaround (option 2) seems to be most appropriate until the correct solution is figured out.
Are you aware of any gtk3/gnome application that runs as daemon and has GUI code so we can study its approach? I tried nautilus but didn't find what I was looking for. As suggested in stackoverflow, have a look at g_unix_signal_add.
Meanwhile asking the gtk devs shouldn't hurt, but I tried to contact them via #gtk+ and got no response. Since this is not a bug, it doesn't make much sense to file a bug report, I wonder if there's another channel to reach them.

**Comment by alexxcons** [comment]
Great, sounds like we agree on the plan :smiley:
For option 1, the switch to GtkApplication introduced as well some TODO's and FIXME's into the code which I will check later and possibly create issues. But I still think it's not worth to revert.

I dont know if there are other applications which run daemon + GUI .. I can investigate a bit in this direction.

I will modify this branch in order to use g_unix_signal_add. ( Not sure if thunar as well should run on some non-unix platform? ) .. need to take care to dont do gtk-things in parallel to the gtk-threads.

I just realized that application-shutdown actually is never called on kill / logout, but only while on hold the logout takes that long. So it seems not to be related to the missing shutdown-procedure on logout.
So far I was not able to reproduce this long-lasting logout with a minimal gtk3 project. Still not sure why thunar behaves like that ... need to further investigate that to be able to file a gtk-bug ( or maybe an issue :smile:  )

**Comment by alexxcons** [comment]
Wow, nautilus was a awesome hint! I just realized that it has exactly the same 8 second delay on logout than thunar :smile: So it looks like it is not thunar's fault.
EDIT: Cannot reproduce this behavior of nautilus .. happens occasionally, but not sure any more that nautilus is the reason. 

Nautilus uses the same API: [g_application_hold() if environment var NAUTILUS_PERSIST is set](https://github.com/GNOME/nautilus/blob/master/src/nautilus-main.c#L99).
However nautilus just does not release this hold ever.

Now I am ready to ask in #gtk+  ... need to do so when I have some time to idle, since I only have one irc bouncer. Still missing a small demo-app to reproduce.

**Comment by alexxcons** [comment]
Maybe just spotted [another way to react to session-logout](https://people.gnome.org/~mccann/gnome-session/docs/gnome-session.html#org.gnome.SessionManager::SessionOver): ... need to learn how to connect to DBUs signals.

**Comment by alexxcons** [comment]
gna, I cannot properly reproduce the 8sec. delay in nautilus. Either the delay came from somewhere else, or I need to do something very specific to trigger it in nautilus.

The approach to connect to a GDBus "SessionOver" signal seems to be not perfect either. Problem is, that there is no standard dbus-signal of all session-managers. For "org.gnome.SessionManager" the Signal is "SessionOver" but for "xfce4-session" I would need to connect to "StateChanged" in order to recognize a logout . Using this approach, we either could try to connect to all possible session-managers, or we could say that thunar only works real good with "xfce4-session".  Both options IMO are not real nice. 

While searching in the gtk+ and nautilus bugzilla I found a feature which was added 2012: ["simplify logout notification API"](https://bugzilla.gnome.org/show_bug.cgi?id=667610)
It's about a signal which will be emmited by GtkApplication on logout. Need to figure out what happened to this feature.  I asked about that on the [gtk-app-devel mailing-list](https://mail.gnome.org/archives/gtk-app-devel-list/2017-July/msg00006.html). ( Dont have time to idle on #gtk+ )

**Comment by alexxcons** [comment]
squashed and rebased current fix into gtk3 ..... followup of possibly better solution will be on bugzilla: https://bugzilla.xfce.org/show_bug.cgi?id=13726

**Pull request closed without merging**
